services:
  backend:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    env_file:
      - .env

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app